name: shell

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      timeout:
        description: "session timeout in minutes"
        required: true
        default: 10

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  connect:
    name: connect
    runs-on: ubuntu-latest
    timeout-minutes: ${{ github.event.inputs.timeout || 10 }}
    steps:
      - name: Setup SSH server for Actor
        uses: alexellis/setup-sshd-actor@master
      - name: Connect to the actuated SSH gateway
        uses: alexellis/actuated-ssh-gateway-action@master
        with:
          gatewayaddr: ${{ secrets.SSH_GATEWAY_IP }}
          secure: true
      - name: Get connection info
        run: |
          list=$(curl -s -L -S ${{ secrets.SSH_GATEWAY_IP }}/list)
          echo $list
          echo "Connection info" >> $GITHUB_STEP_SUMMARY
          echo "$list" | grep "$GITHUB_ACTOR" >> $GITHUB_STEP_SUMMARY
  shell:
    name: connect
    runs-on: ubuntu-latest
    timeout-minutes: ${{ github.event.inputs.timeout || 10 }}
    steps:
      - name: Setup a blocking tmux session
        uses: alexellis/block-with-tmux-action@master
